src/Entity/Recipe/Ingredient.php
<?php

namespace App\Entity\Recipe;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\Recipe\IngredientRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

#[ApiResource]
#[ORM\Entity(repositoryClass: IngredientRepository::class)]
class Ingredient
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $type = null;

    #[ORM\Column(nullable: true)]
    private ?float $caloriesPer100g = null;

    #[ORM\Column(nullable: true)]
    private ?float $proteinsPer100g = null;

    #[ORM\Column(nullable: true)]
    private ?float $fatsPer100g = null;

    #[ORM\Column(nullable: true)]
    private ?float $carbsPer100g = null;

    #[ORM\Column(nullable: true)]
    private ?float $fibersPer100g = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $dataSource = null;

    /**
     * @var Collection<int, RecipeIngredient>
     */
    #[ORM\OneToMany(targetEntity: RecipeIngredient::class, mappedBy: 'ingredient', orphanRemoval: true)]
    private Collection $recipeIngredients;

    public function __construct()
    {
        $this->recipeIngredients = new ArrayCollection();
    }

    public function __toString(): string
    {
        return $this->name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getType(): ?string
    {
        return $this->type;
    }

    public function setType(string $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getCaloriesPer100g(): ?float
    {
        return $this->caloriesPer100g;
    }

    public function setCaloriesPer100g(?float $caloriesPer100g): static
    {
        $this->caloriesPer100g = $caloriesPer100g;

        return $this;
    }

    public function getProteinsPer100g(): ?float
    {
        return $this->proteinsPer100g;
    }

    public function setProteinsPer100g(?float $proteinsPer100g): static
    {
        $this->proteinsPer100g = $proteinsPer100g;

        return $this;
    }

    public function getFatsPer100g(): ?float
    {
        return $this->fatsPer100g;
    }

    public function setFatsPer100g(?float $fatsPer100g): static
    {
        $this->fatsPer100g = $fatsPer100g;

        return $this;
    }

    public function getCarbsPer100g(): ?float
    {
        return $this->carbsPer100g;
    }

    public function setCarbsPer100g(?float $carbsPer100g): static
    {
        $this->carbsPer100g = $carbsPer100g;

        return $this;
    }

    public function getFibersPer100g(): ?float
    {
        return $this->fibersPer100g;
    }

    public function setFibersPer100g(?float $fibersPer100g): static
    {
        $this->fibersPer100g = $fibersPer100g;

        return $this;
    }

    public function getDataSource(): ?string
    {
        return $this->dataSource;
    }

    public function setDataSource(?string $dataSource): static
    {
        $this->dataSource = $dataSource;

        return $this;
    }

    /**
     * @return Collection<int, RecipeIngredient>
     */
    public function getRecipeIngredients(): Collection
    {
        return $this->recipeIngredients;
    }

    public function addRecipeIngredient(RecipeIngredient $recipeIngredient): static
    {
        if (!$this->recipeIngredients->contains($recipeIngredient)) {
            $this->recipeIngredients->add($recipeIngredient);
            $recipeIngredient->setIngredient($this);
        }

        return $this;
    }

    public function removeRecipeIngredient(RecipeIngredient $recipeIngredient): static
    {
        if ($this->recipeIngredients->removeElement($recipeIngredient)) {
            // set the owning side to null (unless already changed)
            if ($recipeIngredient->getIngredient() === $this) {
                $recipeIngredient->setIngredient(null);
            }
        }

        return $this;
    }
}

src/Entity/Recipe/Recipe.php
<?php

namespace App\Entity\Recipe;

use ApiPlatform\Metadata\ApiResource;
use App\Enum\MealTypeEnum;
use App\Repository\Recipe\RecipeRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ApiResource]
#[ORM\Entity(repositoryClass: RecipeRepository::class)]
class Recipe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(length: 255, nullable: true, enumType: MealTypeEnum::class)]
    private ?MealTypeEnum $type = null;

    #[ORM\Column]
    private ?int $preparation_time = null;

    #[ORM\Column(nullable: true)]
    private ?int $cooking_time = null;

    #[ORM\Column]
    private ?int $servings = null;

    #[ORM\Column]
    private ?int $difficulty = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $origin = null;

    /**
     * @var Collection<int, RecipeStep>
     */
    #[ORM\OneToMany(targetEntity: RecipeStep::class, mappedBy: 'recipe', orphanRemoval: true)]
    private Collection $steps;

    /**
     * @var Collection<int, RecipeIngredient>
     */
    #[ORM\OneToMany(targetEntity: RecipeIngredient::class, mappedBy: 'recipe', orphanRemoval: true)]
    private Collection $Ingredients;

    /**
     * @var Collection<int, Utensil>
     */
    #[ORM\ManyToMany(targetEntity: Utensil::class)]
    private Collection $utensils;

    public function __construct()
    {
        $this->steps = new ArrayCollection();
        $this->Ingredients = new ArrayCollection();
        $this->utensils = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getType(): ?MealTypeEnum
    {
        return $this->type;
    }

    public function setType(?MealTypeEnum $type): static
    {
        $this->type = $type;

        return $this;
    }

    public function getPreparationTime(): ?int
    {
        return $this->preparation_time;
    }

    public function setPreparationTime(int $preparation_time): static
    {
        $this->preparation_time = $preparation_time;

        return $this;
    }

    public function getCookingTime(): ?int
    {
        return $this->cooking_time;
    }

    public function setCookingTime(?int $cooking_time): static
    {
        $this->cooking_time = $cooking_time;

        return $this;
    }

    public function getServings(): ?int
    {
        return $this->servings;
    }

    public function setServings(int $servings): static
    {
        $this->servings = $servings;

        return $this;
    }

    public function getDifficulty(): ?int
    {
        return $this->difficulty;
    }

    public function setDifficulty(int $difficulty): static
    {
        $this->difficulty = $difficulty;

        return $this;
    }

    public function getOrigin(): ?string
    {
        return $this->origin;
    }

    public function setOrigin(?string $origin): static
    {
        $this->origin = $origin;

        return $this;
    }

    /**
     * @return Collection<int, RecipeStep>
     */
    public function getSteps(): Collection
    {
        return $this->steps;
    }

    public function addStep(RecipeStep $step): static
    {
        if (!$this->steps->contains($step)) {
            $this->steps->add($step);
            $step->setRecipe($this);
        }

        return $this;
    }

    public function removeStep(RecipeStep $step): static
    {
        if ($this->steps->removeElement($step)) {
            // set the owning side to null (unless already changed)
            if ($step->getRecipe() === $this) {
                $step->setRecipe(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, RecipeIngredient>
     */
    public function getIngredients(): Collection
    {
        return $this->Ingredients;
    }

    public function addIngredient(RecipeIngredient $ingredient): static
    {
        if (!$this->Ingredients->contains($ingredient)) {
            $this->Ingredients->add($ingredient);
            $ingredient->setRecipe($this);
        }

        return $this;
    }

    public function removeIngredient(RecipeIngredient $ingredient): static
    {
        if ($this->Ingredients->removeElement($ingredient)) {
            // set the owning side to null (unless already changed)
            if ($ingredient->getRecipe() === $this) {
                $ingredient->setRecipe(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Utensil>
     */
    public function getUtensils(): Collection
    {
        return $this->utensils;
    }

    public function addUtensil(Utensil $utensil): static
    {
        if (!$this->utensils->contains($utensil)) {
            $this->utensils->add($utensil);
        }

        return $this;
    }

    public function removeUtensil(Utensil $utensil): static
    {
        $this->utensils->removeElement($utensil);

        return $this;
    }
}

src/Entity/Recipe/RecipeIngredient.php
<?php

namespace App\Entity\Recipe;

use ApiPlatform\Metadata\ApiResource;
use App\Enum\UnitEnum;
use App\Repository\Recipe\RecipeIngredientRepository;
use Doctrine\ORM\Mapping as ORM;

#[ApiResource]
#[ORM\Entity(repositoryClass: RecipeIngredientRepository::class)]
class RecipeIngredient
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?float $quantity = null;

    #[ORM\Column(length: 255, enumType: UnitEnum::class)]
    private ?UnitEnum $unit = null;

    #[ORM\ManyToOne(inversedBy: 'Ingredients')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Recipe $recipe = null;

    #[ORM\ManyToOne(inversedBy: 'recipeIngredients')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Ingredient $ingredient = null;


    public function __toString(): string
    {
        return $this->ingredient->getName() . ' ' . $this->getQuantity() . ' ' . $this->getUnit()->enumToString();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getQuantity(): ?float
    {
        return $this->quantity;
    }

    public function setQuantity(float $quantity): static
    {
        $this->quantity = $quantity;

        return $this;
    }

    public function getUnit(): ?UnitEnum
    {
        return $this->unit;
    }

    public function setUnit(UnitEnum $unit): static
    {
        $this->unit = $unit;

        return $this;
    }

    public function getRecipe(): ?Recipe
    {
        return $this->recipe;
    }

    public function setRecipe(?Recipe $recipe): static
    {
        $this->recipe = $recipe;

        return $this;
    }

    public function getIngredient(): ?Ingredient
    {
        return $this->ingredient;
    }

    public function setIngredient(?Ingredient $ingredient): static
    {
        $this->ingredient = $ingredient;

        return $this;
    }
}

src/Entity/Recipe/RecipeStep.php
<?php

namespace App\Entity\Recipe;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\Recipe\RecipeStepRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ApiResource]
#[ORM\Entity(repositoryClass: RecipeStepRepository::class)]
class RecipeStep
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column]
    private ?int $stepOrder = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $instruction = null;

    #[ORM\ManyToOne(inversedBy: 'steps')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Recipe $recipe = null;

    public function __toString(): string
    {
        return $this->stepOrder;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStepOrder(): ?int
    {
        return $this->stepOrder;
    }

    public function setStepOrder(int $stepOrder): static
    {
        $this->stepOrder = $stepOrder;

        return $this;
    }

    public function getInstruction(): ?string
    {
        return $this->instruction;
    }

    public function setInstruction(string $instruction): static
    {
        $this->instruction = $instruction;

        return $this;
    }

    public function getRecipe(): ?Recipe
    {
        return $this->recipe;
    }

    public function setRecipe(?Recipe $recipe): static
    {
        $this->recipe = $recipe;

        return $this;
    }
}

src/Entity/Recipe/Utensil.php
<?php

namespace App\Entity\Recipe;

use ApiPlatform\Metadata\ApiResource;
use App\Repository\Recipe\UtensilRepository;
use Doctrine\ORM\Mapping as ORM;

#[ApiResource]
#[ORM\Entity(repositoryClass: UtensilRepository::class)]
class Utensil
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    public function __toString(): string
    {
        return $this->name;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }
}

src/Controller/FrontEnd/RecipeController.php
<?php

namespace App\Controller\FrontEnd;

use App\Entity\Recipe\Recipe;
use App\Repository\Recipe\RecipeRepository;
use App\Service\NutritionalValuesService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class RecipeController extends AbstractController
{
    public function __construct(
        private NutritionalValuesService $nutritionalValuesService,
    ){
    }

    #[Route('/{_locale<%app.supported_locales%>}/recipes', name: 'recipe_index')]
    public function index(RecipeRepository $repo): Response
    {
        return $this->render('recipe/index.html.twig', [
            'recipes' => $repo->findAll(),
        ]);
    }

    #[Route('/{_locale<%app.supported_locales%>}/recipes/{id}', name: 'recipe_show')]
    public function show(Recipe $recipe): Response
    {
        return $this->render('recipe/show.html.twig', [
            'nutritionalData' => $this->nutritionalValuesService->getValuesForRecipe($recipe),
            'recipe' => $recipe,
        ]);
    }
}

templates/recipe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Recipes{% endblock %}

{% block body %}
    <h1>🍽 Recipes</h1>
    <div class="row">
        {% for recipe in recipes %}
            <div class="card mx-3 col" style="max-width: 400px;">
                <div class="row g-0">
                    <div class="col-md-4">
                        <img src="#" class="img-fluid rounded-start" alt="ToDo">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{ recipe.name }}</h5>
                            <p class="card-text">{{ recipe.description }}</p>
                            <a class="btn btn-primary" href="{{ path('recipe_show', {id: recipe.id}) }}">{{ "Read"|trans }}</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}

templates/recipe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ recipe.name }}{% endblock %}

{% block body %}
    <div class="container mt-5">
        <h1 class="display-4 mb-3">{{ recipe.name }}</h1>

{#        {% if recipe.photo %}#}
{#            <img src="{{ asset('uploads/recipes/' ~ recipe.photo) }}" class="img-fluid rounded mb-4" alt="{{ recipe.name }}">#}
{#        {% endif %}#}

        <div class="mb-4">
            <p class="lead">{{ recipe.description }}</p>
            <span class="badge bg-primary">{{ 'Difficulty'|trans }}: {{ recipe.difficulty }}</span>
            <span class="badge bg-success">{{ recipe.type.enumToString }}</span>
        </div>

        <div class="row mb-4">
            <div class="col-md-3">
                <strong>🕒 {{ 'Preparation'|trans }}</strong><br>{{ recipe.preparationTime }} min
            </div>
            <div class="col-md-3">
                <strong>🔥 {{ 'Cooking'|trans }}</strong><br>{{ recipe.cookingTime }} min
            </div>
            <div class="col-md-3">
                <strong>👥 {{ 'Servings'|trans }}</strong><br>{{ recipe.servings }}
            </div>
            <div class="col-md-3">
                <strong>⚡ {{ 'Calories/serving'|trans }}</strong><br> {{ nutritionalData['calories']}} kcal
            </div>
        </div>

        <hr>

        <h2>🥣 {{ 'Ingredients'|trans }}</h2>
        <ul class="list-group mb-4">
            {% for ri in recipe.ingredients %}
                <li class="list-group-item">
                    {{ ri.quantity }} {{ ri.unit.label|default(ri.unit.enumToString|lower) }} of {{ ri.ingredient.name }}
                </li>
            {% endfor %}
        </ul>

        <h2>🍴 {{ 'Utensils'|trans }}</h2>
        <ul class="list-inline mb-4">
            {% for utensil in recipe.utensils %}
                <li class="list-inline-item badge bg-secondary me-2">{{ utensil.name }}</li>
            {% else %}
                <li>{{ 'No specific utensils required.'|trans }}</li>
            {% endfor %}
        </ul>

        <h2>📋 {{ 'Steps'|trans }}</h2>
        <ol class="list-group list-group-numbered mb-4">
            {% for step in recipe.steps|sort((a, b) => a.stepOrder <=> b.stepOrder) %}
                <li class="list-group-item">{{ step.instruction }}</li>
            {% endfor %}
        </ol>

        <h2>📊 {{ 'Nutritionnal data'|trans }}</h2>
        <div class="card mb-4">
            <div class="card-body">
                <div class="row">
                    <div class="col">
                        <h3>{{ 'Calories'|trans }}</h3>
                        <p>{{ nutritionalData['calories']}} kcal</p>
                    </div>
                    <div class="col">
                        <h3>{{ 'Proteins'|trans }}</h3>
                        <p>{{ nutritionalData['proteins']}} g</p>
                    </div>
                    <div class="col">
                        <h3>{{ 'Fats'|trans }}</h3>
                        <p>{{ nutritionalData['fats']}} g</p>
                    </div>
                    <div class="col">
                        <h3>{{ 'Carbs'|trans }}</h3>
                        <p>{{ nutritionalData['carbs']}} g</p>
                    </div>
                    <div class="col">
                        <h3>{{ 'Fibers'|trans }}</h3>
                        <p>{{ nutritionalData['fibers']}} g</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}